name: Feature Request
description: Request something to be added to Lumen
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: What feature do you want to get added on Lumen Engine?
    validations:
      required: true
